import { Inter } from "next/font/google";
import "./globals.css";
import Menu from "./components/Navbar/Menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Menu /> */}
        <main>{children}</main>
        {/* <footer>This is footer</footer> */}
      </body>
    </html>
  );
}
